In [32]:
import envs
# import agents
# import random
import numpy as np

In [14]:
env = envs.MinesweeperEnvBaby(flatten=False)

# Baby

In [18]:
from stable_baselines3 import PPO, A2C
env = envs.MinesweeperEnvBaby()
model = PPO.load('ms_ppo0', env=env)

In [31]:
observation = env.reset()
done = False
rew = 0
action, _state = model.predict(observation, deterministic=False)
observation, reward, done, info = env.step(action)
print(env.observation[1:-1,1:-1])

while not done:
    action, _state = model.predict(observation, deterministic=False)
    observation, reward, done, info = env.step(action)
    # env.print_render()
    # print(action, reward, (~env.display[1:-1,1:-1].astype(bool)).sum(), env.bombs)
    rew += reward
print('attempt', env.attempt)
print('reward', reward)
print('total reward', rew)
print(info, done)
print((~env.display[1:-1,1:-1].astype(bool)).sum())
env.print_render()


[[1. 1. 2. 1. 0.]
 [1. 9. 2. 9. 0.]
 [2. 2. 3. 1. 0.]
 [2. 9. 2. 0. 0.]
 [0. 9. 0. 0. 0.]]
attempt 25
reward -1
total reward 44
{'attempt': 25, 'remaining': 2.0, 'revealed': 19.0, 'hit': 'uncovered'} True
3
[[1. 9. 2. 1. 0.]
 [1. 9. 2. 9. 0.]
 [2. 9. 3. 1. 0.]
 [2. 9. 2. 0. 0.]
 [0. 9. 0. 0. 0.]]


In [12]:
%%time
remainings = []
attempts = []
wins = []
for _ in range(100):
    observation = env.reset()
    done = False
    while not done:
        action, _state = model.predict(observation, deterministic=True)
        # print(env._translate_action(action))
        # env.print_render()
        observation, reward, done, info = env.step(action)
    attempts.append(info["attempt"])
    remainings.append(info["remaining"])
    wins.append(info["remaining"] == 0)
print(f'average wins: {np.mean(wins)}')
print(f'average attempts: {np.mean(attempts)}')
print(f'average remaining: {np.mean(remainings)}')

average wins: 0.85
average attempts: 11.14
average remaining: 0.18
CPU times: user 717 ms, sys: 5.36 ms, total: 722 ms
Wall time: 730 ms


# Beginner

In [53]:
from stable_baselines3 import PPO, A2C
env = envs.MinesweeperEnvBeginner()
model = PPO.load('ms_beginner_ppo1', env=env)

In [55]:
%%time
remainings = []
attempts = []
wins = []
for _ in range(500):
    observation = env.reset()
    done = False
    while not done:
        action, _state = model.predict(observation, deterministic=True)
        # print(env._translate_action(action))
        # env.print_render()
        observation, reward, done, info = env.step(action)
    attempts.append(info["attempt"])
    remainings.append(info["remaining"])
    wins.append(info["remaining"] == 0)
print(f'average wins: {np.mean(wins)}')
print(f'average attempts: {np.mean(attempts)}')
print(f'average remaining: {np.mean(remainings)}')

average wins: 0.402
average attempts: 28.13
average remaining: 2.758
CPU times: user 15.1 s, sys: 23.3 ms, total: 15.1 s
Wall time: 15.1 s


In [56]:
env = envs.MinesweeperEnvBeginner()
model = PPO.load('ms_beginner_ppo2', env=env)

In [57]:
%%time
remainings = []
attempts = []
wins = []
for _ in range(500):
    observation = env.reset()
    done = False
    while not done:
        action, _state = model.predict(observation, deterministic=True)
        # print(env._translate_action(action))
        # env.print_render()
        observation, reward, done, info = env.step(action)
    attempts.append(info["attempt"])
    remainings.append(info["remaining"])
    wins.append(info["remaining"] == 0)
print(f'average wins: {np.mean(wins)}')
print(f'average attempts: {np.mean(attempts)}')
print(f'average remaining: {np.mean(remainings)}')

average wins: 0.6
average attempts: 22.5
average remaining: 2.546
CPU times: user 12.1 s, sys: 12 ms, total: 12.1 s
Wall time: 12.1 s


In [58]:
env = envs.MinesweeperEnvBeginner()
model = PPO.load('ms_beginner_ppo3', env=env)

In [59]:
%%time
remainings = []
attempts = []
wins = []
for _ in range(500):
    observation = env.reset()
    done = False
    while not done:
        action, _state = model.predict(observation, deterministic=True)
        # print(env._translate_action(action))
        # env.print_render()
        observation, reward, done, info = env.step(action)
    attempts.append(info["attempt"])
    remainings.append(info["remaining"])
    wins.append(info["remaining"] == 0)
print(f'average wins: {np.mean(wins)}')
print(f'average attempts: {np.mean(attempts)}')
print(f'average remaining: {np.mean(remainings)}')

average wins: 0.684
average attempts: 20.928
average remaining: 1.892
CPU times: user 11.3 s, sys: 27.9 ms, total: 11.3 s
Wall time: 11.3 s
