In [1]:
import envs
# import agents
# import random
import numpy as np

In [2]:
env = envs.SudokuEnv2(flatten=False)

In [3]:
env.reset()

array([[[2., 8., 4., 0., 9., 7., 0., 6., 5.],
        [0., 9., 0., 0., 0., 0., 0., 0., 0.],
        [7., 0., 6., 0., 0., 0., 9., 4., 3.],
        [0., 0., 9., 7., 1., 0., 4., 5., 0.],
        [5., 4., 3., 0., 2., 6., 0., 1., 9.],
        [0., 0., 7., 0., 0., 0., 2., 3., 0.],
        [4., 0., 0., 0., 0., 8., 0., 9., 1.],
        [1., 0., 8., 5., 4., 9., 6., 2., 0.],
        [0., 6., 5., 0., 0., 2., 3., 0., 0.]],

       [[1., 1., 1., 0., 1., 1., 0., 1., 1.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 1., 0., 0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1., 0., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 0., 1., 1.],
        [0., 0., 1., 0., 0., 0., 1., 1., 0.],
        [1., 0., 0., 0., 0., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 1., 1., 1., 0.],
        [0., 1., 1., 0., 0., 1., 1., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0

In [4]:
len(env.pairs)

38

In [5]:
(env.start == 0).sum()

38

In [6]:
env.solution

array([[2, 8, 4, 3, 9, 7, 1, 6, 5],
       [3, 9, 1, 4, 6, 5, 8, 7, 2],
       [7, 5, 6, 2, 8, 1, 9, 4, 3],
       [8, 2, 9, 7, 1, 3, 4, 5, 6],
       [5, 4, 3, 8, 2, 6, 7, 1, 9],
       [6, 1, 7, 9, 5, 4, 2, 3, 8],
       [4, 7, 2, 6, 3, 8, 5, 9, 1],
       [1, 3, 8, 5, 4, 9, 6, 2, 7],
       [9, 6, 5, 1, 7, 2, 3, 8, 4]])

In [10]:
done = False
observation = env.reset()
while not done:
    observation, reward, done, info = env.step(env.solution[env.current_square_coord])
observation, reward, done, info

(array([[[4., 3., 9., 6., 5., 8., 1., 2., 7.],
         [1., 7., 8., 3., 2., 4., 6., 5., 9.],
         [5., 6., 2., 9., 7., 1., 4., 3., 8.],
         [6., 1., 3., 8., 9., 2., 7., 4., 5.],
         [8., 4., 5., 7., 1., 6., 3., 9., 2.],
         [2., 9., 7., 5., 4., 3., 8., 6., 1.],
         [9., 8., 4., 2., 6., 7., 5., 1., 3.],
         [3., 5., 6., 1., 8., 9., 2., 7., 4.],
         [7., 2., 1., 4., 3., 5., 9., 8., 6.]],
 
        [[1., 0., 1., 0., 0., 0., 0., 1., 1.],
         [0., 0., 1., 1., 0., 1., 0., 0., 1.],
         [1., 1., 0., 0., 1., 1., 1., 0., 1.],
         [1., 1., 1., 1., 1., 1., 0., 0., 0.],
         [1., 1., 0., 1., 0., 0., 0., 0., 1.],
         [0., 0., 1., 1., 1., 1., 0., 1., 0.],
         [0., 0., 0., 1., 1., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0., 0., 0., 1.],
         [0., 1., 0., 0., 1., 0., 0., 0., 1.]],
 
        [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       

In [14]:
(env.start == 0).sum()

45

In [12]:
len(env.pairs)

45

In [19]:
observation

array([[[6., 7., 5., 8., 3., 4., 1., 9., 2.],
        [4., 1., 9., 6., 2., 5., 3., 8., 7.],
        [8., 3., 2., 7., 9., 1., 4., 6., 5.],
        [2., 5., 1., 9., 6., 8., 7., 4., 3.],
        [3., 9., 4., 1., 7., 2., 6., 5., 8.],
        [7., 8., 6., 5., 4., 3., 9., 2., 1.],
        [5., 4., 7., 3., 8., 9., 2., 1., 6.],
        [1., 2., 3., 4., 5., 6., 8., 7., 9.],
        [9., 6., 8., 2., 1., 7., 5., 3., 4.]],

       [[0., 1., 1., 1., 1., 0., 0., 0., 1.],
        [0., 1., 1., 1., 1., 1., 1., 0., 0.],
        [1., 0., 1., 0., 0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 0., 0., 0., 0., 0.],
        [0., 1., 1., 1., 0., 0., 1., 0., 0.],
        [1., 1., 1., 0., 0., 1., 1., 0., 1.],
        [1., 0., 1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 1., 1., 0., 1., 0., 1., 0.],
        [0., 1., 1., 0., 1., 0., 1., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0

In [10]:
from stable_baselines3 import PPO, A2C
env = envs.MinesweeperEnvBaby()
model = PPO.load('ms_ppo0', env=env)

In [31]:
observation = env.reset()
done = False
rew = 0
action, _state = model.predict(observation, deterministic=False)
observation, reward, done, info = env.step(action)
print(env.observation[1:-1,1:-1])

while not done:
    action, _state = model.predict(observation, deterministic=False)
    observation, reward, done, info = env.step(action)
    # env.print_render()
    # print(action, reward, (~env.display[1:-1,1:-1].astype(bool)).sum(), env.bombs)
    rew += reward
print('attempt', env.attempt)
print('reward', reward)
print('total reward', rew)
print(info, done)
print((~env.display[1:-1,1:-1].astype(bool)).sum())
env.print_render()


[[1. 1. 2. 1. 0.]
 [1. 9. 2. 9. 0.]
 [2. 2. 3. 1. 0.]
 [2. 9. 2. 0. 0.]
 [0. 9. 0. 0. 0.]]
attempt 25
reward -1
total reward 44
{'attempt': 25, 'remaining': 2.0, 'revealed': 19.0, 'hit': 'uncovered'} True
3
[[1. 9. 2. 1. 0.]
 [1. 9. 2. 9. 0.]
 [2. 9. 3. 1. 0.]
 [2. 9. 2. 0. 0.]
 [0. 9. 0. 0. 0.]]


In [12]:
%%time
remainings = []
attempts = []
wins = []
for _ in range(100):
    observation = env.reset()
    done = False
    while not done:
        action, _state = model.predict(observation, deterministic=True)
        # print(env._translate_action(action))
        # env.print_render()
        observation, reward, done, info = env.step(action)
    attempts.append(info["attempt"])
    remainings.append(info["remaining"])
    wins.append(info["remaining"] == 0)
print(f'average wins: {np.mean(wins)}')
print(f'average attempts: {np.mean(attempts)}')
print(f'average remaining: {np.mean(remainings)}')

average wins: 0.85
average attempts: 11.14
average remaining: 0.18
CPU times: user 717 ms, sys: 5.36 ms, total: 722 ms
Wall time: 730 ms


# Beginner

In [34]:
from stable_baselines3 import PPO, A2C
env = envs.MinesweeperEnvBeginner()
model = PPO.load('ms_beginner_ppo1', env=env)

In [35]:
observation = env.reset()
done = False
rew = 0
action, _state = model.predict(observation, deterministic=False)
observation, reward, done, info = env.step(action)
print(env.observation[1:-1,1:-1])

while not done:
    action, _state = model.predict(observation, deterministic=False)
    observation, reward, done, info = env.step(action)
    # env.print_render()
    # print(action, reward, (~env.display[1:-1,1:-1].astype(bool)).sum(), env.bombs)
    rew += reward
print('attempt', env.attempt)
print('reward', reward)
print('total reward', rew)
print(info, done)
print((~env.display[1:-1,1:-1].astype(bool)).sum())
env.print_render()


[[0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 2. 1. 1. 0. 0. 0.]
 [1. 9. 3. 9. 3. 2. 1. 0.]
 [1. 2. 9. 4. 9. 9. 2. 0.]
 [0. 1. 3. 9. 5. 9. 3. 0.]
 [0. 0. 2. 9. 3. 1. 3. 9.]
 [0. 0. 1. 1. 1. 0. 2. 9.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
attempt 6
reward -100
total reward -60
{'attempt': 6, 'remaining': 1.0, 'revealed': 53.0, 'hit': 'bomb'} True
9
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 2. 1. 1. 0. 0. 0.]
 [1. 9. 3. 9. 3. 2. 1. 0.]
 [1. 2. 9. 4. 9. 9. 2. 0.]
 [0. 1. 3. 9. 9. 9. 3. 0.]
 [0. 0. 2. 9. 3. 1. 3. 9.]
 [0. 0. 1. 1. 1. 0. 2. 9.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [37]:
%%time
remainings = []
attempts = []
wins = []
for _ in range(100):
    observation = env.reset()
    done = False
    while not done:
        action, _state = model.predict(observation, deterministic=True)
        # print(env._translate_action(action))
        # env.print_render()
        observation, reward, done, info = env.step(action)
    attempts.append(info["attempt"])
    remainings.append(info["remaining"])
    wins.append(info["remaining"] == 0)
print(f'average wins: {np.mean(wins)}')
print(f'average attempts: {np.mean(attempts)}')
print(f'average remaining: {np.mean(remainings)}')

average wins: 0.44
average attempts: 26.35
average remaining: 2.94
CPU times: user 3.14 s, sys: 7.22 ms, total: 3.14 s
Wall time: 3.15 s


In [41]:
from stable_baselines3 import PPO, A2C
env = envs.MinesweeperEnvBeginner()
model = PPO.load('ms_beginner_ppo2', env=env)

In [42]:
observation = env.reset()
done = False
rew = 0
action, _state = model.predict(observation, deterministic=False)
observation, reward, done, info = env.step(action)
print(env.observation[1:-1,1:-1])

while not done:
    action, _state = model.predict(observation, deterministic=False)
    observation, reward, done, info = env.step(action)
    # env.print_render()
    # print(action, reward, (~env.display[1:-1,1:-1].astype(bool)).sum(), env.bombs)
    rew += reward
print('attempt', env.attempt)
print('reward', reward)
print('total reward', rew)
print(info, done)
print((~env.display[1:-1,1:-1].astype(bool)).sum())
env.print_render()


[[1. 1. 1. 0. 1. 1. 1. 0.]
 [1. 9. 2. 1. 2. 9. 1. 0.]
 [1. 1. 2. 9. 3. 3. 4. 0.]
 [1. 1. 2. 1. 2. 9. 9. 9.]
 [1. 9. 1. 0. 1. 2. 3. 0.]
 [2. 2. 3. 1. 1. 0. 0. 0.]
 [1. 9. 3. 9. 1. 0. 0. 0.]
 [0. 0. 9. 0. 0. 0. 0. 0.]]
attempt 23
reward 10
total reward 220
{'attempt': 23, 'remaining': 0.0, 'revealed': 54.0, 'hit': 'safe'} True
5
[[1. 1. 1. 0. 1. 1. 1. 0.]
 [1. 9. 2. 1. 2. 9. 1. 0.]
 [1. 1. 2. 9. 3. 3. 4. 0.]
 [1. 1. 2. 1. 2. 9. 9. 9.]
 [1. 9. 1. 0. 1. 2. 3. 0.]
 [2. 2. 3. 1. 1. 0. 0. 0.]
 [1. 9. 3. 9. 1. 0. 0. 0.]
 [0. 0. 9. 0. 0. 0. 0. 0.]]


In [43]:
%%time
remainings = []
attempts = []
wins = []
for _ in range(100):
    observation = env.reset()
    done = False
    while not done:
        action, _state = model.predict(observation, deterministic=True)
        # print(env._translate_action(action))
        # env.print_render()
        observation, reward, done, info = env.step(action)
    attempts.append(info["attempt"])
    remainings.append(info["remaining"])
    wins.append(info["remaining"] == 0)
print(f'average wins: {np.mean(wins)}')
print(f'average attempts: {np.mean(attempts)}')
print(f'average remaining: {np.mean(remainings)}')

average wins: 0.6
average attempts: 21.99
average remaining: 2.47
CPU times: user 2.58 s, sys: 5.44 ms, total: 2.58 s
Wall time: 2.59 s


In [45]:
coords = [(i, j) for i in range(9) for j in range(9)]

In [46]:
np.random.shuffle(pairs) 

In [50]:
2%81

2

In [47]:
pairs

[(8, 7),
 (6, 3),
 (4, 2),
 (5, 0),
 (4, 4),
 (1, 2),
 (5, 6),
 (5, 1),
 (1, 4),
 (6, 7),
 (4, 6),
 (3, 7),
 (6, 1),
 (0, 6),
 (4, 8),
 (7, 6),
 (8, 8),
 (5, 7),
 (2, 6),
 (1, 5),
 (7, 8),
 (7, 7),
 (0, 1),
 (6, 8),
 (3, 0),
 (1, 6),
 (8, 6),
 (7, 4),
 (7, 3),
 (4, 1),
 (2, 4),
 (1, 8),
 (0, 5),
 (3, 1),
 (6, 0),
 (4, 3),
 (3, 8),
 (8, 2),
 (2, 2),
 (3, 5),
 (1, 3),
 (2, 7),
 (0, 2),
 (2, 3),
 (3, 3),
 (2, 8),
 (0, 4),
 (3, 2),
 (4, 0),
 (8, 5),
 (5, 8),
 (0, 8),
 (7, 1),
 (0, 0),
 (4, 5),
 (0, 7),
 (5, 2),
 (3, 6),
 (1, 0),
 (8, 1),
 (5, 4),
 (5, 5),
 (0, 3),
 (4, 7),
 (8, 0),
 (6, 5),
 (7, 0),
 (2, 0),
 (5, 3),
 (2, 1),
 (6, 4),
 (7, 5),
 (7, 2),
 (1, 7),
 (3, 4),
 (6, 2),
 (8, 4),
 (1, 1),
 (2, 5),
 (6, 6),
 (8, 3)]